name: CI (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install project (dev)
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          if (Test-Path pyproject.toml) {
            pip install -e ".[dev,test,telegram,llama]"
          } else {
            pip install -r requirements.txt
          }

      - name: Run tests
        shell: pwsh
        env:
          CLAUDE_SKIP_PERMISSIONS: "true"
        run: |
          pytest -q

